/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import Entidades.Empresas;
import Entidades.Funcionarios;
import Entidades.Multas;
import Entidades.Veiculos;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.EmpresasBO;
import negocio.FuncionariosBO;
import negocio.MultasBO;
import negocio.NegocioException;
import negocio.VeiculosBO;
/**
 *
 * @author Wallace
 */

public class JDProcMulta extends javax.swing.JDialog {

    /**
     * Creates new form JDListaEmpresas
     */
    public static JFIMultas multa;
    public JDProcMulta(JFIMultas parent, boolean modal) {
        //super(parent, modal);
        this.multa=parent;
        this.setModal(true);
        
        initComponents();
        this.pack();
             String placa;
         DefaultTableModel model = (DefaultTableModel) tabla.getModel();
                            model.setRowCount(0);
                            MultasBO bo=new MultasBO();
                            try{
                                List<Multas> lista=bo.listar();
                                for(Multas lstmultas:lista){

                                VeiculosBO boveiculos = new VeiculosBO();
                                        try { 

                                           Veiculos veiculo=boveiculos.consultar(lstmultas.getRenavam());

                                            placa=veiculo.getPlaca();
                                            model.addRow(new Object[]{lstmultas.getAIT(),placa,lstmultas.getMotivo(),lstmultas.getValor(),lstmultas.getValordesc()});
                                        } catch (NegocioException ex) {
                                            Logger.getLogger(JFIMultas.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                                        
                                }
                                }catch(NegocioException ex){

                                }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpbusca = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnselecionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtbusca = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LISTAGEM DE EMPRESAS");
        setModal(true);
        setResizable(false);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "AIT", "Placa", "Motivo", "Valor s/ Desconto", "Valor c/ Desconto"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MULTAS");

        btnselecionar.setText("SELECIONAR");
        btnselecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselecionarActionPerformed(evt);
            }
        });

        jLabel2.setText("Buscar por:");

        txtbusca.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                txtbuscaHierarchyChanged(evt);
            }
        });
        txtbusca.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtbuscaInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtbusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscaActionPerformed(evt);
            }
        });
        txtbusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addComponent(btnselecionar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtbusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnselecionar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnselecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselecionarActionPerformed
        // TODO add your handling code here:
        
        this.multa.setAIT(tabla.getValueAt(tabla.getSelectedRow(),0).toString());

        this.setVisible(false);
        
    }//GEN-LAST:event_btnselecionarActionPerformed

    private void txtbuscaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtbuscaInputMethodTextChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtbuscaInputMethodTextChanged

    private void txtbuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscaKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtbuscaKeyPressed

    private void txtbuscaHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_txtbuscaHierarchyChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_txtbuscaHierarchyChanged

    private void txtbuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscaActionPerformed
        // TODO add your handling code here:
                  
    }//GEN-LAST:event_txtbuscaActionPerformed

    private void txtbuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscaKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtbuscaKeyTyped

    private void txtbuscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscaKeyReleased
        // TODO add your handling code here:
        String placa;
         DefaultTableModel model = (DefaultTableModel) tabla.getModel();
                            model.setRowCount(0);
                            MultasBO bo=new MultasBO();
                            try{
                                List<Multas> lista=bo.listar(txtbusca.getText());
                                for(Multas lstmultas:lista){

                                VeiculosBO boveiculos = new VeiculosBO();
                                        try { 

                                           Veiculos veiculo=boveiculos.consultar(lstmultas.getRenavam());

                                            placa=veiculo.getPlaca();
                                            model.addRow(new Object[]{lstmultas.getAIT(),placa,lstmultas.getMotivo(),lstmultas.getValor(),lstmultas.getValordesc()});
                                        } catch (NegocioException ex) {
                                            Logger.getLogger(JFIMultas.class.getName()).log(Level.SEVERE, null, ex);
                                        }
                                                        
                                }
                                }catch(NegocioException ex){

                                }
    }//GEN-LAST:event_txtbuscaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDProcMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDProcMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDProcMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDProcMulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDProcMulta dialog = new JDProcMulta(multa, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                      
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
public String convertbol(boolean valor){
     if(valor){
        return ("SIM");
     }else{
         return("NÃO");
     }   
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnselecionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.ButtonGroup tpbusca;
    private javax.swing.JTextField txtbusca;
    // End of variables declaration//GEN-END:variables
}
