/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;


import static Apresentacao.JFIVeiculos.frota;
import Entidades.Cargos;
import Entidades.Classificacao;
import Entidades.Empresas;
import Entidades.Funcionarios;
import Entidades.Logins;
import Entidades.Multas;
import Entidades.Unidades;
import Entidades.Veiculos;
import Utilitarios.Utilitarios;
import com.toedter.calendar.JDateChooser;
import dados.DadosException;
import java.awt.Component;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.channels.FileChannel;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Date;

import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeString.substring;
import negocio.CargosBO;
import negocio.ClassificacaoBO;
import negocio.EmpresasBO;
import negocio.FuncionariosBO;
import negocio.LoginsBO;
import negocio.MultasBO;
import negocio.NegocioException;
import negocio.UnidadesBO;
import negocio.VeiculosBO;

/**
 *
 * @author Wallace
 */
public class JFIMultas extends javax.swing.JInternalFrame {
private String User;

public static JDProcMulta multa;
    private Object vencpagamento;
    public String getUser() {
        return User;
    }

    public void setUser(String User) {
        this.User = User;
    }
    /**
     * Creates new form JFIFuncionarios
     */
    public JFIMultas(String usuario) {
       super();
        initComponents();
        this.setUser(usuario);
   new Utilitarios().LimpaTela(this);
       cmboriginaria.removeAllItems();
      cmboriginaria.addItem("");
        MultasBO bomulta=new MultasBO();
          try{
                List<Multas> lista=bomulta.listar();
                
                for(Multas lstmultas:lista){

                //Object[] linha = //alguma linha

                //model.addRow(linha);
                    
                    cmboriginaria.addItem(lstmultas.getAIT());
                    
                }
            }catch(NegocioException ex){

            }
      cmbplaca.removeAllItems();
      
        VeiculosBO bo=new VeiculosBO();
          try{
                List<Veiculos> lista=bo.listar();
                for(Veiculos lst:lista){

                //Object[] linha = //alguma linha

                //model.addRow(linha);
                    
                    cmbplaca.addItem(lst.getPlaca());
                    
                }
            }catch(NegocioException ex){

            }
      cmbfunc.removeAllItems();
      cmbfunc.addItem("");
        FuncionariosBO bofunc=new FuncionariosBO();
          try{
                List<Funcionarios> lista=bofunc.listar();
                for(Funcionarios lstfunc:lista){

                //Object[] linha = //alguma linha

                //model.addRow(linha);
                    
                    cmbfunc.addItem(lstfunc.getNome());
                    
                }
            }catch(NegocioException ex){

            }
    
      
            Component[] componentes =  JpanelMultas.getComponents(); // altere para o nome da variavel do seu painel
                for (Component componente : componentes) {
                    componente.setEnabled(false);
                }
            LoginsBO bologins = new LoginsBO();
        try {
            
            Logins login=bologins.consultar(usuario);
            if(login.getNivel()==0 || login.getNivel()==1){
                lbltermo.setVisible(true);
                txttermo.setVisible(true);
                btnloctermo.setVisible(true);
                lbldtdesc.setVisible(true);
                dtdesc.setVisible(true);
            }else{
                lbltermo.setVisible(false);
                txttermo.setVisible(false);
                btnloctermo.setVisible(false);
                lbldtdesc.setVisible(false);
                dtdesc.setVisible(false);
            }
        }catch(NegocioException ex){

        }

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpanelMultas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmotivo = new javax.swing.JTextField();
        cmboriginaria = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtait = new javax.swing.JTextField();
        lblrenavam = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cmbplaca = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txtlocal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbfunc = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtvlcdesc = new javax.swing.JTextField();
        txtvlsdesc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        chkdesconto = new javax.swing.JCheckBox();
        chkidentificacao = new javax.swing.JCheckBox();
        txtnotificacao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnlocalizar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtboleto = new javax.swing.JTextField();
        btnlocalizar1 = new javax.swing.JButton();
        lbltermo = new javax.swing.JLabel();
        txttermo = new javax.swing.JTextField();
        btnloctermo = new javax.swing.JButton();
        Dtvencpag = new com.toedter.calendar.JDateChooser();
        DtvencImp = new com.toedter.calendar.JDateChooser();
        DtInf = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtmunicipio = new javax.swing.JTextField();
        txthora = new javax.swing.JFormattedTextField();
        lblait = new javax.swing.JLabel();
        txtcomprovante = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnlocalizar3 = new javax.swing.JButton();
        lbldtdesc = new javax.swing.JLabel();
        dtdesc = new com.toedter.calendar.JDateChooser();
        dtpag = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtContRemocao = new javax.swing.JTextField();
        btnlocalizar4 = new javax.swing.JButton();
        btnnova = new javax.swing.JButton();
        btnsalvar = new javax.swing.JButton();
        btnconsultar = new javax.swing.JButton();
        btnprocurar = new javax.swing.JButton();
        btnalterar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        JpanelMultas.setEnabled(false);

        jLabel2.setText("MOTIVO:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CADASTRO DE MULTAS");

        cmboriginaria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("AIT ORIGINÁRIA:");

        jLabel12.setText("AIT:");

        txtait.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                txtaitAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        txtait.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaitKeyTyped(evt);
            }
        });

        lblrenavam.setEnabled(false);
        lblrenavam.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                lblrenavamHierarchyChanged(evt);
            }
        });

        jLabel13.setText("PLACA:");

        jLabel17.setText("LOCAL:");

        cmbplaca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel18.setText("DATA:");

        jLabel1.setText("HORA:");

        jLabel6.setText("VENC. IND. CONDUTOR:");

        jLabel7.setText("VENCIMENTO:");

        jLabel8.setText("FUNCIONÁRIO:");

        cmbfunc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel10.setText("VALOR C/ DESC:");

        txtvlcdesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvlcdescActionPerformed(evt);
            }
        });
        txtvlcdesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtvlcdescKeyTyped(evt);
            }
        });

        txtvlsdesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvlsdescActionPerformed(evt);
            }
        });
        txtvlsdesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtvlsdescKeyTyped(evt);
            }
        });

        jLabel11.setText("VALOR S/ DESC:");

        chkdesconto.setText("DESCONTO EM FOLHA");

        chkidentificacao.setText("IDENTIFICAÇÃO DO CONDUTOR");

        txtnotificacao.setEditable(false);
        txtnotificacao.setEnabled(false);

        jLabel9.setText("NOTIFICAÇÃO:");

        btnlocalizar.setText("Localizar");
        btnlocalizar.setEnabled(false);
        btnlocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlocalizarActionPerformed(evt);
            }
        });

        jLabel14.setText("BOLETO:");

        txtboleto.setEditable(false);
        txtboleto.setEnabled(false);

        btnlocalizar1.setText("Localizar");
        btnlocalizar1.setEnabled(false);
        btnlocalizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlocalizar1ActionPerformed(evt);
            }
        });

        lbltermo.setText("TERMO DE DESCONTO:");

        txttermo.setEditable(false);
        txttermo.setEnabled(false);

        btnloctermo.setText("Localizar");
        btnloctermo.setEnabled(false);
        btnloctermo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloctermoActionPerformed(evt);
            }
        });

        jLabel3.setText("MUNICÍPIO:");

        txthora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance())));

        txtcomprovante.setEditable(false);
        txtcomprovante.setEnabled(false);

        jLabel16.setText("COMPROVANTE DE PAGAMENTO:");

        btnlocalizar3.setText("Localizar");
        btnlocalizar3.setEnabled(false);
        btnlocalizar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlocalizar3ActionPerformed(evt);
            }
        });

        lbldtdesc.setText("DT. DE DESCONTO:");

        jLabel20.setText("DT. PAGAMENTO:");

        jLabel21.setText("CONTROLE DE REMOÇÃO:");

        txtContRemocao.setEditable(false);
        txtContRemocao.setEnabled(false);

        btnlocalizar4.setText("Localizar");
        btnlocalizar4.setEnabled(false);
        btnlocalizar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlocalizar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpanelMultasLayout = new javax.swing.GroupLayout(JpanelMultas);
        JpanelMultas.setLayout(JpanelMultasLayout);
        JpanelMultasLayout.setHorizontalGroup(
            JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelMultasLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(lblait, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblrenavam, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(JpanelMultasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(179, 179, 179))
            .addGroup(JpanelMultasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelMultasLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addGap(36, 36, 36)
                        .addComponent(txtmotivo)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtnotificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnlocalizar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(JpanelMultasLayout.createSequentialGroup()
                        .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(JpanelMultasLayout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(txtmunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtlocal, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(JpanelMultasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelMultasLayout.createSequentialGroup()
                        .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelMultasLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel7))
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtpag, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dtvencpag, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelMultasLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtvlcdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtvlsdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtboleto, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnlocalizar1))
                            .addGroup(JpanelMultasLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcomprovante, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnlocalizar3))))
                    .addGroup(JpanelMultasLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(29, 29, 29)
                        .addComponent(cmbfunc, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(chkdesconto)
                        .addGap(18, 18, 18)
                        .addComponent(chkidentificacao)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(txtContRemocao, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnlocalizar4))
                    .addGroup(JpanelMultasLayout.createSequentialGroup()
                        .addComponent(lbltermo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttermo, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnloctermo)
                        .addGap(18, 18, 18)
                        .addComponent(lbldtdesc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelMultasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(36, 36, 36)
                .addComponent(txtait, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(cmbplaca, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DtInf, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmboriginaria, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DtvencImp, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        JpanelMultasLayout.setVerticalGroup(
            JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelMultasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblrenavam, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblait, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtait, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmboriginaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DtInf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DtvencImp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtmunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtnotificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlocalizar))
                .addGap(18, 18, 18)
                .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cmbfunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkdesconto)
                        .addComponent(chkidentificacao)
                        .addComponent(jLabel21)
                        .addComponent(txtContRemocao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnlocalizar4)))
                .addGap(18, 18, 18)
                .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelMultasLayout.createSequentialGroup()
                        .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltermo)
                            .addComponent(txttermo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnloctermo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Dtvencpag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(txtvlcdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(txtvlsdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtboleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnlocalizar1)
                                .addComponent(jLabel14)))
                        .addGap(19, 19, 19)
                        .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(dtpag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20))
                            .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16)
                                .addComponent(txtcomprovante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnlocalizar3)))
                        .addGap(41, 41, 41))
                    .addGroup(JpanelMultasLayout.createSequentialGroup()
                        .addGroup(JpanelMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbldtdesc)
                            .addComponent(dtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        btnnova.setText("NOVO");
        btnnova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnovaActionPerformed(evt);
            }
        });

        btnsalvar.setText("SALVAR");
        btnsalvar.setEnabled(false);
        btnsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvarActionPerformed(evt);
            }
        });

        btnconsultar.setText("CONSULTAR");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        btnprocurar.setText("PROCURAR");
        btnprocurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprocurarActionPerformed(evt);
            }
        });

        btnalterar.setText("ALTERAR");
        btnalterar.setEnabled(false);
        btnalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterarActionPerformed(evt);
            }
        });

        btncancelar.setText("CANCELAR");
        btncancelar.setEnabled(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(btnnova)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnconsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btnprocurar)
                        .addGap(17, 17, 17)
                        .addComponent(btnalterar)
                        .addGap(18, 18, 18)
                        .addComponent(btncancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JpanelMultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JpanelMultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnova)
                    .addComponent(btnsalvar)
                    .addComponent(btnconsultar)
                    .addComponent(btnalterar)
                    .addComponent(btncancelar)
                    .addComponent(btnprocurar))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnovaActionPerformed
        // TODO add your handling code here:
   
          JpanelMultas.setEnabled(true); 
         Component[] componentes =  JpanelMultas.getComponents(); // altere para o nome da variavel do seu painel
         for (Component componente : componentes) {
                    componente.setEnabled(true);
                }
                for (int i=0; i < JpanelMultas.getComponentCount(); i++) {
                    //varre todos os componentes
                    Component c = JpanelMultas.getComponent(i);
                    if (c instanceof JTextField) {
                        //apaga os valores
                        JTextField field = (JTextField) c;
                        field.setText("");
                     
                    }
           }
       cmboriginaria.removeAllItems();
       MultasBO bomultas= new MultasBO();
       try{
           cmboriginaria.addItem("");
            List<Multas> listamulta=bomultas.listar();
            for(Multas lstmultas:listamulta){
                cmboriginaria.addItem(lstmultas.getAIT());
            }
            
       } catch (NegocioException ex) {
        Logger.getLogger(JFIMultas.class.getName()).log(Level.SEVERE, null, ex);
    }
         
            cmbplaca.removeAllItems();
      
        VeiculosBO bo=new VeiculosBO();
          try{
                List<Veiculos> lista=bo.listar();
                for(Veiculos lst:lista){

                //Object[] linha = //alguma linha

                //model.addRow(linha);
                    
                    cmbplaca.addItem(lst.getPlaca());
                    
                }
            }catch(NegocioException ex){

            }
 
           
      //cmboriginaria.addItem("");
        

    
                
                btnprocurar.setEnabled(false);
                btnnova.setEnabled(false);
                btnsalvar.setEnabled(true);
                btnconsultar.setEnabled(false);
                btnalterar.setEnabled(false);
                btncancelar.setEnabled(true);
                           
    }//GEN-LAST:event_btnnovaActionPerformed
    
    private void btnsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvarActionPerformed
        // TODO add your handling code here:
        
       
        boolean obrigatorios=false;
        Multas multas= new Multas();
        Date dataHoraAtual = new Date();
        
       if((!txtait.getText().isEmpty())&&(DtInf.getDate()!=null)&&(!txthora.getText().isEmpty())&&(DtvencImp.getDate()!=null)){
           obrigatorios=true;
       }
        
       if(obrigatorios){
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        String data = new SimpleDateFormat("dd-MM-yyyy").format(dataHoraAtual);
        String hora = new SimpleDateFormat("HH:mm:ss").format(dataHoraAtual);
        String dtvenc, dtvencimp,dtinfracao,originaria,matricula,dtpagamento,dtdesconto;
        int renavam;
       
     
        File diretorio = new File("S:\\Multas\\"+ txtait.getText());
        diretorio.mkdir(); 
         
    
       
        Time horainf=Time.valueOf(txthora.getText().toString());
        multas.setAIT(txtait.getText());
        multas.setRenavam(HEIGHT);
       if(DtInf.getDate()!=null){
           java.util.Date pega3 =DtInf.getDate() ;
            dtinfracao=formato.format(pega3);
            multas.setDtinf(java.sql.Date.valueOf(dtinfracao));
       }
        multas.setHorainf(horainf);
        multas.setAITorig(cmboriginaria.getSelectedItem().toString());
       if(DtvencImp.getDate()!=null){
          
            java.util.Date pega2 =DtvencImp.getDate() ;
            dtvencimp=formato.format(pega2);
            multas.setVencimp(java.sql.Date.valueOf(dtvencimp));
       }
      
       
        multas.setMotivo(txtmotivo.getText());
        multas.setMunicipio(txtmunicipio.getText());
        multas.setLocal(txtlocal.getText());
        multas.setDescontofolha(chkdesconto.isSelected());
        multas.setIdentificacao(chkidentificacao.isSelected());
        if(Dtvencpag.getDate()!=null){
             java.util.Date pega =Dtvencpag.getDate() ;
           dtvenc=formato.format(pega); 
            multas.setVecimento(java.sql.Date.valueOf(dtvenc));
        }
        if (txtvlcdesc.getText().isEmpty()){
           txtvlcdesc.setText("0");
        }
            multas.setValordesc(0.0);
       
        if(txtvlsdesc.getText().isEmpty()){
            txtvlsdesc.setText("0");
        }
         multas.setValor(Double.parseDouble(txtvlsdesc.getText()));
       if(!txtnotificacao.getText().isEmpty()){
           File arquivoExemploOrigem = new File(txtnotificacao.getText());
           File arquivoExemploDestinoCopiar = new File("S:\\Multas\\"+ txtait.getText() +"\\notificacao.pdf");
             try {
           
            //Primeiro modo de copiar o arquivo de um local para outro
            copy(arquivoExemploOrigem, arquivoExemploDestinoCopiar);
            multas.setNotificacao(arquivoExemploDestinoCopiar.toString());
             } catch (IOException e) {
            e.printStackTrace();
        }
       }
          if(!txtboleto.getText().isEmpty()){
           File arquivoExemploOrigem = new File(txtboleto.getText());
           File arquivoExemploDestinoCopiar = new File("S:\\Multas\\"+ txtait.getText() +"\\boleto.pdf");
             try {
           
            //Primeiro modo de copiar o arquivo de um local para outro
            copy(arquivoExemploOrigem, arquivoExemploDestinoCopiar);
            multas.setBoleto(arquivoExemploDestinoCopiar.toString());
             } catch (IOException e) {
            e.printStackTrace();
        }
       }   
        if(!txttermo.getText().isEmpty()){
           File arquivoExemploOrigem = new File(txttermo.getText());
           File arquivoExemploDestinoCopiar = new File("S:\\Multas\\"+ txtait.getText() +"\\termo.pdf");
             try {
           
            //Primeiro modo de copiar o arquivo de um local para outro
            copy(arquivoExemploOrigem, arquivoExemploDestinoCopiar);
             multas.setTermo(arquivoExemploDestinoCopiar.toString());
             } catch (IOException e) {
            e.printStackTrace();
        }
       }    
           if(dtpag.getDate()!=null){
          
            java.util.Date pega4 =dtpag.getDate() ;
            dtpagamento=formato.format(pega4);
            multas.setDtpag(java.sql.Date.valueOf(dtpagamento));
       }
        if(dtdesc.getDate()!=null){
          
            java.util.Date pega5 =dtdesc.getDate() ;
            dtdesconto=formato.format(pega5);
            multas.setDtdesc(java.sql.Date.valueOf(dtdesconto));
       }
          if(!txtcomprovante.getText().isEmpty()){
           File arquivoExemploOrigem = new File(txtcomprovante.getText());
           File arquivoExemploDestinoCopiar = new File("S:\\Multas\\"+ txtait.getText() +"\\comprovante.pdf");
             try {
           
            //Primeiro modo de copiar o arquivo de um local para outro
            copy(arquivoExemploOrigem, arquivoExemploDestinoCopiar);
             multas.setComprovante(arquivoExemploDestinoCopiar.toString());
             } catch (IOException e) {
            e.printStackTrace();
        }
       }  
      
        multas.setUser(this.getUser());
         data=data.substring(6,10)+"-"+data.substring(3,5)+"-"+data.substring(0,2);
        multas.setDt(java.sql.Date.valueOf(data));
        if (!txthora.getText().toString().isEmpty()){
            multas.setHora(java.sql.Time.valueOf(hora));
        }
        VeiculosBO boveiculos = new VeiculosBO();
        try { 
            
           Veiculos veiculo=boveiculos.consultar(cmbplaca.getSelectedItem().toString());
            
            renavam=veiculo.getRenavam();
            multas.setRenavam(renavam);
            
        } catch (NegocioException ex) {
            Logger.getLogger(JFIFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(cmboriginaria.getSelectedItem().toString()!=""){
            MultasBO booriginarias = new MultasBO();
            try { 

               Multas originarias=booriginarias.consultar(cmboriginaria.getSelectedItem().toString());

                originaria=originarias.getAIT();
                multas.setAITorig(originaria);

            } catch (NegocioException ex) {
                Logger.getLogger(JFIFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(!cmbfunc.getSelectedItem().toString().isEmpty()) {
            FuncionariosBO bofunc = new FuncionariosBO();
            try { 

               Funcionarios funcionario=bofunc.consultar(cmbfunc.getSelectedItem().toString());

                matricula=funcionario.getMatricula();
                multas.setMatricula(matricula);
                JOptionPane.showMessageDialog(null, matricula);
            } catch (NegocioException ex) {
                Logger.getLogger(JFIFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        MultasBO bo = new MultasBO();
        try {
            bo.inserir(multas);
                Component[] componentes =  JpanelMultas.getComponents(); // altere para o nome da variavel do seu painel
                for (Component componente : componentes) {
                    componente.setEnabled(false);
                }
                for (int i=0; i < JpanelMultas.getComponentCount(); i++) {
                    //varre todos os componentes
                    Component c = JpanelMultas.getComponent(i);
                    if (c instanceof JTextField) {
                        //apaga os valores
                        JTextField field = (JTextField) c;
                        field.setText("");
                        
                    }
           }
        btnnova.setEnabled(true);
        btnsalvar.setEnabled(false);
        btnconsultar.setEnabled(true);
        btnalterar.setEnabled(false);
        btncancelar.setEnabled(false);    
        btnprocurar.setEnabled(true);    
        } catch (NegocioException ex) {
            Logger.getLogger(JFIMultas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
        Component[] componentes1 =  JpanelMultas.getComponents(); // altere para o nome da variavel do seu painel// altere para o nome da variavel do seu painel
        
   
        
        
       }else{
           JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios!");
       }
    }//GEN-LAST:event_btnsalvarActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        // TODO add your handling code here:
       String consulta=JOptionPane.showInputDialog("Digite a AIT da Multa:");
       MultasBO bo = new MultasBO();
         try {
            
            Multas multa=bo.consultar(consulta);
                Component[] componentes =  JpanelMultas.getComponents(); // altere para o nome da variavel do seu painel
                for (Component componente : componentes) {
                    componente.setEnabled(true);
                }
            txtait.setText(multa.getAIT());
            DtInf.setDate(multa.getDtinf());
            txthora.setText(multa.getHorainf().toString());
            if(multa.getVencimp()!=null){
                DtvencImp.setDate(multa.getVencimp());
            }
             if(multa.getDtpag()!=null){
                dtpag.setDate(multa.getDtpag());
            }
            if(multa.getDtdesc()!=null){
                dtdesc.setDate(multa.getDtdesc());
            }
            txtmotivo.setText(multa.getMotivo());
            txtmunicipio.setText(multa.getMunicipio());
            txtlocal.setText(multa.getLocal());
            chkdesconto.setSelected(multa.isDescontofolha());
            chkidentificacao.setSelected(multa.isIdentificacao());
            if(multa.getVecimento()!=null){
                Dtvencpag.setDate(multa.getVecimento());
            }
            txtvlcdesc.setText(multa.getValordesc().toString());
            txtvlsdesc.setText(multa.getValor().toString());
            txttermo.setText(multa.getTermo());
            txtnotificacao.setText(multa.getNotificacao());
            txtboleto.setText(multa.getBoleto());
            txtcomprovante.setText(multa.getComprovante());
            VeiculosBO boveiculos = new VeiculosBO();
            try { 

               Veiculos veiculo=boveiculos.consultar(multa.getRenavam());
               
                cmbplaca.setSelectedItem(veiculo.getPlaca());

            } catch (NegocioException ex) {
                Logger.getLogger(JFIMultas.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(!multa.getAITorig().isEmpty()){
                cmboriginaria.setSelectedItem(multa.getAITorig());
            }else{
                cmboriginaria.setSelectedIndex(0);
            }
            if(multa.getMatricula()!=null){
                FuncionariosBO bofuncionarios = new FuncionariosBO();
               try { 

                  Funcionarios funcionario=bofuncionarios.consultar(multa.getMatricula());

                   cmbfunc.setSelectedItem(funcionario.getNome());

               } catch (NegocioException ex) {
                   Logger.getLogger(JFIMultas.class.getName()).log(Level.SEVERE, null, ex);
               }
            }
            JpanelMultas.setEnabled(true);
            btnnova.setEnabled(false);
            btnsalvar.setEnabled(false);
            btnconsultar.setEnabled(false);
            btnalterar.setEnabled(true);
            btncancelar.setEnabled(true);
            txtait.setEnabled(false);
         }catch(NegocioException ex){
             Logger.getLogger(JFIMultas.class.getName()).log(Level.SEVERE, null, ex);
         }  

    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btnalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterarActionPerformed
     boolean obrigatorios=false;
        Multas multas= new Multas();
        Date dataHoraAtual = new Date();
        
       if((!txtait.getText().isEmpty())&&(DtInf.getDate()!=null)&&(!txthora.getText().isEmpty())&&(DtvencImp.getDate()!=null)){
           obrigatorios=true;
       }
        
       if(obrigatorios){
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        String data = new SimpleDateFormat("dd-MM-yyyy").format(dataHoraAtual);
        String hora = new SimpleDateFormat("HH:mm:ss").format(dataHoraAtual);
        String dtvenc, dtvencimp,dtinfracao,originaria,matricula,dtpagamento,dtdesconto;
        int renavam;
       
     
        File diretorio = new File("S:\\Multas\\"+ txtait.getText());
        diretorio.mkdir(); 
         
    
       
        Time horainf=Time.valueOf(txthora.getText().toString());
        multas.setAIT(txtait.getText());
        multas.setRenavam(HEIGHT);
       if(DtInf.getDate()!=null){
           java.util.Date pega3 =DtInf.getDate() ;
            dtinfracao=formato.format(pega3);
            multas.setDtinf(java.sql.Date.valueOf(dtinfracao));
       }
        multas.setHorainf(horainf);
        multas.setAITorig(cmboriginaria.getSelectedItem().toString());
       if(DtvencImp.getDate()!=null){
          
            java.util.Date pega2 =DtvencImp.getDate() ;
            dtvencimp=formato.format(pega2);
            multas.setVencimp(java.sql.Date.valueOf(dtvencimp));
       }
        multas.setMotivo(txtmotivo.getText());
        multas.setMunicipio(txtmunicipio.getText());
        multas.setLocal(txtlocal.getText());
        multas.setDescontofolha(chkdesconto.isSelected());
        multas.setIdentificacao(chkidentificacao.isSelected());
        if(Dtvencpag.getDate()!=null){
             java.util.Date pega =Dtvencpag.getDate() ;
           dtvenc=formato.format(pega); 
            multas.setVecimento(java.sql.Date.valueOf(dtvenc));
        }
        if (txtvlcdesc.getText().isEmpty()){
           txtvlcdesc.setText("0");
        }
        multas.setValordesc(Double.parseDouble(txtvlcdesc.getText()));
       
        if(txtvlsdesc.getText().isEmpty()){
            txtvlsdesc.setText("0");
        }
         multas.setValor(Double.parseDouble(txtvlsdesc.getText()));
       if(!txtnotificacao.getText().isEmpty()){
           File arquivoExemploOrigem = new File(txtnotificacao.getText());
           File arquivoExemploDestinoCopiar = new File("S:\\Multas\\"+ txtait.getText() +"\\notificacao.pdf");
             try {
           
            //Primeiro modo de copiar o arquivo de um local para outro
            copy(arquivoExemploOrigem, arquivoExemploDestinoCopiar);
            multas.setNotificacao(arquivoExemploDestinoCopiar.toString());
             } catch (IOException e) {
            e.printStackTrace();
        }
       }
          if(!txtboleto.getText().isEmpty()){
           File arquivoExemploOrigem = new File(txtboleto.getText());
           File arquivoExemploDestinoCopiar = new File("S:\\Multas\\"+ txtait.getText() +"\\boleto.pdf");
             try {
           
            //Primeiro modo de copiar o arquivo de um local para outro
            copy(arquivoExemploOrigem, arquivoExemploDestinoCopiar);
            multas.setBoleto(arquivoExemploDestinoCopiar.toString());
             } catch (IOException e) {
            e.printStackTrace();
        }
       }   
        if(!txttermo.getText().isEmpty()){
           File arquivoExemploOrigem = new File(txttermo.getText());
           File arquivoExemploDestinoCopiar = new File("S:\\Multas\\"+ txtait.getText() +"\\termo.pdf");
             try {
           
            //Primeiro modo de copiar o arquivo de um local para outro
            copy(arquivoExemploOrigem, arquivoExemploDestinoCopiar);
             multas.setTermo(arquivoExemploDestinoCopiar.toString());
             } catch (IOException e) {
            e.printStackTrace();
        }
       }      
        if(dtpag.getDate()!=null){
          
            java.util.Date pega4 =dtpag.getDate() ;
            dtpagamento=formato.format(pega4);
            multas.setDtpag(java.sql.Date.valueOf(dtpagamento));
       }
        if(dtdesc.getDate()!=null){
          
            java.util.Date pega5 =dtdesc.getDate() ;
            dtdesconto=formato.format(pega5);
            multas.setDtdesc(java.sql.Date.valueOf(dtdesconto));
       }
          if(!txtcomprovante.getText().isEmpty()){
           File arquivoExemploOrigem = new File(txtcomprovante.getText());
           File arquivoExemploDestinoCopiar = new File("S:\\Multas\\"+ txtait.getText() +"\\comprovante.pdf");
             try {
           
            //Primeiro modo de copiar o arquivo de um local para outro
            copy(arquivoExemploOrigem, arquivoExemploDestinoCopiar);
             multas.setComprovante(arquivoExemploDestinoCopiar.toString());
             } catch (IOException e) {
            e.printStackTrace();
        }
       }  
      
        multas.setUser(this.getUser());
         data=data.substring(6,10)+"-"+data.substring(3,5)+"-"+data.substring(0,2);
        multas.setDt(java.sql.Date.valueOf(data));
        if (!txthora.getText().toString().isEmpty()){
            multas.setHora(java.sql.Time.valueOf(hora));
        }
        VeiculosBO boveiculos = new VeiculosBO();
        try { 
            
           Veiculos veiculo=boveiculos.consultar(cmbplaca.getSelectedItem().toString());
            
            renavam=veiculo.getRenavam();
            multas.setRenavam(renavam);
            
        } catch (NegocioException ex) {
            Logger.getLogger(JFIFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(!cmboriginaria.getSelectedItem().toString().isEmpty()){
            MultasBO booriginarias = new MultasBO();
            try { 

               Multas originarias=booriginarias.consultar(cmboriginaria.getSelectedItem().toString());

                originaria=originarias.getAIT();
                multas.setAITorig(originaria);

            } catch (NegocioException ex) {
                Logger.getLogger(JFIFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(!cmbfunc.getSelectedItem().toString().isEmpty()) {
            FuncionariosBO bofunc = new FuncionariosBO();
            try { 

               Funcionarios funcionario=bofunc.consultar(cmbfunc.getSelectedItem().toString());

                matricula=funcionario.getMatricula();
                multas.setMatricula(matricula);
                JOptionPane.showMessageDialog(null, matricula);
            } catch (NegocioException ex) {
                Logger.getLogger(JFIFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        MultasBO bo = new MultasBO();
        try {
            bo.alterar(multas);
                Component[] componentes =  JpanelMultas.getComponents(); // altere para o nome da variavel do seu painel
                for (Component componente : componentes) {
                    componente.setEnabled(false);
                }
                for (int i=0; i < JpanelMultas.getComponentCount(); i++) {
                    //varre todos os componentes
                    Component c = JpanelMultas.getComponent(i);
                    if (c instanceof JTextField) {
                        //apaga os valores
                        JTextField field = (JTextField) c;
                        field.setText("");
                        
                    }
                     if (c instanceof JDateChooser) {
                        //apaga os valores
                        JDateChooser field = (JDateChooser) c;
                        field.setDate(null);
                        
                    }
                     cmboriginaria.setSelectedIndex(0);
                    
           }
                
        btnnova.setEnabled(true);
        btnsalvar.setEnabled(false);
        btnconsultar.setEnabled(true);
        btnalterar.setEnabled(false);
        btncancelar.setEnabled(false);    
        btnprocurar.setEnabled(true);
        } catch (NegocioException ex) {
            Logger.getLogger(JFIMultas.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex);
        }
       
   
        
        
       }else{
           JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios!");
       }        
        
     
        
    }//GEN-LAST:event_btnalterarActionPerformed
    
    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
         btnnova.setEnabled(true);
        btnsalvar.setEnabled(false);
        btnconsultar.setEnabled(true);
        btnalterar.setEnabled(false);
        btncancelar.setEnabled(false);
        btnprocurar.setEnabled(true);
       Component[] componentes =  JpanelMultas.getComponents(); // altere para o nome da variavel do seu painel
         for (Component componente : componentes) {
                    componente.setEnabled(false);
                }
                for (int i=0; i < JpanelMultas.getComponentCount(); i++) {
                    //varre todos os componentes
                    Component c = JpanelMultas.getComponent(i);
                    if (c instanceof JTextField) {
                        //apaga os valores
                        JTextField field = (JTextField) c;
                        field.setText("");
                        System.out.println("apagando campo " + i);
                    }
                    if (c instanceof JDateChooser) {
                        //apaga os valores
                        JDateChooser field = (JDateChooser) c;
                        field.setDate(null);
                        
                    }
                    
           }
           cmboriginaria.setSelectedIndex(0);
        
    }//GEN-LAST:event_btncancelarActionPerformed
      
    private void btnprocurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprocurarActionPerformed
        // TODO add your handling code here:
         mostramultas();
     
    }//GEN-LAST:event_btnprocurarActionPerformed

    private void lblrenavamHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_lblrenavamHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblrenavamHierarchyChanged

    private void txtaitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaitKeyTyped
        // TODO add your handling code here:
  
    }//GEN-LAST:event_txtaitKeyTyped

    private void txtaitAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_txtaitAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaitAncestorMoved

    private void txtvlcdescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvlcdescKeyTyped
        // TODO add your handling code here:
          String caracteres="0987654321,";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
    }//GEN-LAST:event_txtvlcdescKeyTyped
    }
    private void txtvlcdescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvlcdescActionPerformed
        // TODO add your handling code here:
      
       
    }//GEN-LAST:event_txtvlcdescActionPerformed

    private void txtvlsdescKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvlsdescKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvlsdescKeyTyped

    private void btnlocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlocalizarActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i= file.showSaveDialog(null);
        if (i==1){
            txtnotificacao.setText("");
        } else {
            File arquivo = file.getSelectedFile();
            txtnotificacao.setText(arquivo.getPath());
        }
    }//GEN-LAST:event_btnlocalizarActionPerformed

    private void btnlocalizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlocalizar1ActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i= file.showSaveDialog(null);
        if (i==1){
            txtboleto.setText("");
        } else {
            File arquivo = file.getSelectedFile();
            txtboleto.setText(arquivo.getPath());
        }
    }//GEN-LAST:event_btnlocalizar1ActionPerformed

    private void btnloctermoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloctermoActionPerformed
        // TODO add your handling code here:
          JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i= file.showSaveDialog(null);
        if (i==1){
            txttermo.setText("");
        } else {
            File arquivo = file.getSelectedFile();
            txttermo.setText(arquivo.getPath());
        }
    }//GEN-LAST:event_btnloctermoActionPerformed

    private void btnlocalizar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlocalizar3ActionPerformed
        // TODO add your handling code here:
             JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i= file.showSaveDialog(null);
        if (i==1){
            txtcomprovante.setText("");
        } else {
            File arquivo = file.getSelectedFile();
            txtcomprovante.setText(arquivo.getPath());
        }
    }//GEN-LAST:event_btnlocalizar3ActionPerformed

    private void txtvlsdescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvlsdescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvlsdescActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formInternalFrameClosing

    private void btnlocalizar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlocalizar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlocalizar4ActionPerformed

    
    public void mostramultas(){
   multa = new JDProcMulta(this,true);
   multa.setLocationRelativeTo(null);
   multa.setVisible(true);
}
        /**
     * Copia arquivos de um local para o outro 
     * @param origem - Arquivo de origem 
     * @param destino - Arquivo de destino 
     * @param overwrite - Confirmação para sobrescrever os arquivos 
     * @throws IOException 
     */
    public static void copy(File origem, File destino) throws IOException {
        Date date = new Date();
        InputStream in = new FileInputStream(origem);
        OutputStream out = new FileOutputStream(destino);           
        // Transferindo bytes de entrada para saída
        byte[] buffer = new byte[1024];
        int lenght;
        while ((lenght= in.read(buffer)) > 0) {
            out.write(buffer, 0, lenght);
        }
        in.close();
        out.close();
        Long time = new Date().getTime() - date.getTime();
        System.out.println("Saiu copy"+time);
    }
   
    /** 
     * Copia arquivos de um local para o outro 
     * @param origem - Arquivo de origem 
     * @param destino - Arquivo de destino 
     * @param overwrite - Confirmação para sobrescrever os arquivos 
     * @throws IOException 
     */ 
    
    public static void copy(File origem, File destino, boolean overwrite) throws IOException{ 
        Date date = new Date();
       if (destino.exists() && !overwrite){ 
          System.err.println(destino.getName()+" já existe, ignorando..."); 
          return; 
       } 
       FileInputStream fisOrigem = new FileInputStream(origem); 
       FileOutputStream fisDestino = new FileOutputStream(destino); 
       FileChannel fcOrigem = fisOrigem.getChannel();   
       FileChannel fcDestino = fisDestino.getChannel();   
       fcOrigem.transferTo(0, fcOrigem.size(), fcDestino);   
       fisOrigem.close();   
       fisDestino.close(); 
       Long time = new Date().getTime() - date.getTime();
       System.out.println("Saiu copy"+time);
    }
public void setAIT(String ait) {
    MultasBO bo = new MultasBO();
         try {
            
            Multas multa=bo.consultar(ait);
                Component[] componentes =  JpanelMultas.getComponents(); // altere para o nome da variavel do seu painel
                for (Component componente : componentes) {
                    componente.setEnabled(true);
                }
            txtait.setText(multa.getAIT());
            DtInf.setDate(multa.getDtinf());
            txthora.setText(multa.getHorainf().toString());
            if(multa.getVencimp()!=null){
                DtvencImp.setDate(multa.getVencimp());
            }
            txtmotivo.setText(multa.getMotivo());
            txtmunicipio.setText(multa.getMunicipio());
            txtlocal.setText(multa.getLocal());
            chkdesconto.setSelected(multa.isDescontofolha());
            chkidentificacao.setSelected(multa.isIdentificacao());
            if(multa.getVecimento()!=null){
                Dtvencpag.setDate(multa.getVecimento());
            }
              if(multa.getDtpag()!=null){
                dtpag.setDate(multa.getDtpag());
            }
            if(multa.getDtdesc()!=null){
                dtdesc.setDate(multa.getDtdesc());
            }
            txtcomprovante.setText(multa.getComprovante());
            txtvlcdesc.setText(multa.getValordesc().toString());
            txtvlsdesc.setText(multa.getValor().toString());
            txttermo.setText(multa.getTermo());
            txtnotificacao.setText(multa.getNotificacao());
            txtboleto.setText(multa.getBoleto());
            
            VeiculosBO boveiculos = new VeiculosBO();
            try { 

               Veiculos veiculo=boveiculos.consultar(multa.getRenavam());
               
                cmbplaca.setSelectedItem(veiculo.getPlaca());

            } catch (NegocioException ex) {
                Logger.getLogger(JFIMultas.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(!multa.getAITorig().isEmpty()){
                cmboriginaria.setSelectedItem(multa.getAITorig());
            }else{
                cmboriginaria.setSelectedIndex(0);
            }
            if(multa.getMatricula()!=null){
                FuncionariosBO bofuncionarios = new FuncionariosBO();
               try { 

                  Funcionarios funcionario=bofuncionarios.consultar(multa.getMatricula());

                   cmbfunc.setSelectedItem(funcionario.getNome());

               } catch (NegocioException ex) {
                   Logger.getLogger(JFIMultas.class.getName()).log(Level.SEVERE, null, ex);
               }
            }
            JpanelMultas.setEnabled(true);
            btnnova.setEnabled(false);
            btnsalvar.setEnabled(false);
            btnconsultar.setEnabled(false);
            btnprocurar.setEnabled(false);
            btnalterar.setEnabled(true);
            btncancelar.setEnabled(true);
            txtait.setEnabled(false);
         }catch(NegocioException ex){
             Logger.getLogger(JFIMultas.class.getName()).log(Level.SEVERE, null, ex);
         }  

    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DtInf;
    private com.toedter.calendar.JDateChooser DtvencImp;
    private com.toedter.calendar.JDateChooser Dtvencpag;
    private javax.swing.JPanel JpanelMultas;
    private javax.swing.JButton btnalterar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btnlocalizar;
    private javax.swing.JButton btnlocalizar1;
    private javax.swing.JButton btnlocalizar3;
    private javax.swing.JButton btnlocalizar4;
    private javax.swing.JButton btnloctermo;
    private javax.swing.JButton btnnova;
    private javax.swing.JButton btnprocurar;
    private javax.swing.JButton btnsalvar;
    private javax.swing.JCheckBox chkdesconto;
    private javax.swing.JCheckBox chkidentificacao;
    private javax.swing.JComboBox<String> cmbfunc;
    private javax.swing.JComboBox<String> cmboriginaria;
    private javax.swing.JComboBox<String> cmbplaca;
    private com.toedter.calendar.JDateChooser dtdesc;
    private com.toedter.calendar.JDateChooser dtpag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblait;
    private javax.swing.JLabel lbldtdesc;
    private javax.swing.JLabel lblrenavam;
    private javax.swing.JLabel lbltermo;
    private javax.swing.JTextField txtContRemocao;
    private javax.swing.JTextField txtait;
    private javax.swing.JTextField txtboleto;
    private javax.swing.JTextField txtcomprovante;
    private javax.swing.JFormattedTextField txthora;
    private javax.swing.JTextField txtlocal;
    private javax.swing.JTextField txtmotivo;
    private javax.swing.JTextField txtmunicipio;
    private javax.swing.JTextField txtnotificacao;
    private javax.swing.JTextField txttermo;
    private javax.swing.JTextField txtvlcdesc;
    private javax.swing.JTextField txtvlsdesc;
    // End of variables declaration//GEN-END:variables
}
