/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apresentacao;

import static Apresentacao.JFIMultas.copy;
import Entidades.Cargos;
import Entidades.Multas;
import Entidades.Unidades;
import com.sun.javafx.tk.Toolkit;
import dados.DadosException;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.channels.FileChannel;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.DefaultCellEditor;
import negocio.CargosBO;
import negocio.MultasBO;
import negocio.NegocioException;
import negocio.UnidadesBO;

/**
 *
 * @author Wallace
 */
public class JFIMultasADescontar extends javax.swing.JInternalFrame {

    /**
     * Creates new form JFICargos
     */
private String User;

public static JDProcveiculo frota;
    public String getUser() {
        return User;
    }

    public void setUser(String User) {
        this.User = User;
    }
    public JFIMultasADescontar(String usuario) {
        
        super();
        initComponents();
        this.setUser(usuario);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngpordem = new javax.swing.ButtonGroup();
        btngpopimp = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        JpanelCargos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        VencInicial = new com.toedter.calendar.JDateChooser();
        VencFinal = new com.toedter.calendar.JDateChooser();
        JRBPgDesc = new javax.swing.JRadioButton();
        JRBPagas = new javax.swing.JRadioButton();
        JRBTodas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTmultas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cmddtpag = new javax.swing.JButton();
        JDtDesc = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        JRdSelecionados = new javax.swing.JRadioButton();
        JRdTodos = new javax.swing.JRadioButton();
        cmdboletos = new javax.swing.JButton();
        cmdcomprovantes = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        btnnova1 = new javax.swing.JButton();
        btnsalvar1 = new javax.swing.JButton();
        btnconsultar1 = new javax.swing.JButton();
        btnalterar1 = new javax.swing.JButton();
        btncancelar1 = new javax.swing.JButton();
        JpanelCargos1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtcargo1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtcbo1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblid1 = new javax.swing.JLabel();
        JRBId1 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jtbcargos1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        JRBCargo1 = new javax.swing.JRadioButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CONTROLE DE MULTAS A PAGAR");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1formFocusGained(evt);
            }
        });
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1formComponentShown(evt);
            }
        });

        JpanelCargos.setEnabled(false);

        jLabel2.setText("Entre:");

        jLabel3.setText("E:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MULTAS A DESCONTAR");

        jLabel1.setText("Buscar Multas");

        lblid.setText(" ");
        lblid.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblidInputMethodTextChanged(evt);
            }
        });

        btngpordem.add(JRBPgDesc);
        JRBPgDesc.setSelected(true);
        JRBPgDesc.setText("Pagas Descontadas");
        JRBPgDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBPgDescActionPerformed(evt);
            }
        });

        btngpordem.add(JRBPagas);
        JRBPagas.setText("A Descontar pagas");
        JRBPagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBPagasActionPerformed(evt);
            }
        });

        btngpordem.add(JRBTodas);
        JRBTodas.setText("Todas Pagas");
        JRBTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBTodasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpanelCargosLayout = new javax.swing.GroupLayout(JpanelCargos);
        JpanelCargos.setLayout(JpanelCargosLayout);
        JpanelCargosLayout.setHorizontalGroup(
            JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelCargosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelCargosLayout.createSequentialGroup()
                        .addGroup(JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VencInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(VencFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(JpanelCargosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(JRBPgDesc)
                        .addGap(18, 18, 18)
                        .addComponent(JRBPagas)
                        .addGap(18, 18, 18)
                        .addComponent(JRBTodas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(lblid)
                .addContainerGap(371, Short.MAX_VALUE))
            .addGroup(JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE))
        );
        JpanelCargosLayout.setVerticalGroup(
            JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelCargosLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblid)
                    .addGroup(JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JRBPgDesc)
                        .addComponent(JRBPagas)
                        .addComponent(JRBTodas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(VencInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(VencFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(JpanelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpanelCargosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5)
                    .addContainerGap(94, Short.MAX_VALUE)))
        );

        JTmultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AIT", "FUNCIONARIO", "VALOR C/DESCONTO", "DT. DESCONTO", "BOLETO", "DT. PAGAMENTO", "COMPROVANTE", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JTmultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTmultasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JTmultas);

        jLabel4.setText("Buscar por:");

        cmddtpag.setText("INCLUIR DESCONTO EM");
        cmddtpag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmddtpagActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opções de Impressão"));

        btngpopimp.add(JRdSelecionados);
        JRdSelecionados.setSelected(true);
        JRdSelecionados.setText("Apenas Selecionados");

        btngpopimp.add(JRdTodos);
        JRdTodos.setText("Todos");

        cmdboletos.setText("BOLETOS");
        cmdboletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdboletosActionPerformed(evt);
            }
        });

        cmdcomprovantes.setText("COMPROVANTES");
        cmdcomprovantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcomprovantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JRdTodos)
                            .addComponent(JRdSelecionados)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(cmdboletos)
                        .addGap(44, 44, 44)
                        .addComponent(cmdcomprovantes)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(JRdSelecionados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JRdTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdboletos)
                    .addComponent(cmdcomprovantes))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 106, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105)
                        .addComponent(cmddtpag)
                        .addGap(18, 18, 18)
                        .addComponent(JDtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JpanelCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(JpanelCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JDtDesc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmddtpag, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(116, 116, 116))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);
        jInternalFrame1.setTitle("Cadastro de Cargos");
        jInternalFrame1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jInternalFrame1formFocusGained(evt);
            }
        });
        jInternalFrame1.addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrame1formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                jInternalFrame1formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel2formFocusGained(evt);
            }
        });
        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2formComponentShown(evt);
            }
        });

        btnnova1.setText("NOVO");
        btnnova1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnova1ActionPerformed(evt);
            }
        });

        btnsalvar1.setText("SALVAR");
        btnsalvar1.setEnabled(false);
        btnsalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvar1ActionPerformed(evt);
            }
        });

        btnconsultar1.setText("CONSULTAR");
        btnconsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultar1ActionPerformed(evt);
            }
        });

        btnalterar1.setText("ALTERAR");
        btnalterar1.setEnabled(false);
        btnalterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalterar1ActionPerformed(evt);
            }
        });

        btncancelar1.setText("CANCELAR");
        btncancelar1.setEnabled(false);
        btncancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar1ActionPerformed(evt);
            }
        });

        JpanelCargos1.setEnabled(false);

        jLabel6.setText("Cargo");

        txtcargo1.setEnabled(false);

        jLabel7.setText("CBO");

        txtcbo1.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("CADASTRO DE CARGOS");

        jLabel9.setText("ID Cargo:");

        lblid1.setText(" ");
        lblid1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lblid1InputMethodTextChanged(evt);
            }
        });

        javax.swing.GroupLayout JpanelCargos1Layout = new javax.swing.GroupLayout(JpanelCargos1);
        JpanelCargos1.setLayout(JpanelCargos1Layout);
        JpanelCargos1Layout.setHorizontalGroup(
            JpanelCargos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelCargos1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelCargos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelCargos1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(lblid1))
                    .addGroup(JpanelCargos1Layout.createSequentialGroup()
                        .addGroup(JpanelCargos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JpanelCargos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcargo1)
                            .addComponent(txtcbo1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(449, Short.MAX_VALUE))
            .addGroup(JpanelCargos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpanelCargos1Layout.createSequentialGroup()
                    .addGap(184, 184, 184)
                    .addComponent(jLabel8)
                    .addContainerGap(421, Short.MAX_VALUE)))
        );
        JpanelCargos1Layout.setVerticalGroup(
            JpanelCargos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelCargos1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(JpanelCargos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblid1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelCargos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtcargo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelCargos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtcbo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(JpanelCargos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpanelCargos1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel8)
                    .addContainerGap(94, Short.MAX_VALUE)))
        );

        btngpordem.add(JRBId1);
        JRBId1.setText("ID");
        JRBId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBId1ActionPerformed(evt);
            }
        });

        Jtbcargos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cargo", "CBO"
            }
        ));
        Jtbcargos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jtbcargos1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Jtbcargos1);

        jLabel10.setText("Ordenar por:");

        btngpordem.add(JRBCargo1);
        JRBCargo1.setText("Cargo");
        JRBCargo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRBCargo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(JpanelCargos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(515, 515, 515))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnnova1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsalvar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnconsultar1)
                        .addGap(18, 18, 18)
                        .addComponent(btnalterar1)
                        .addGap(18, 18, 18)
                        .addComponent(btncancelar1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel10)
                        .addGap(39, 39, 39)
                        .addComponent(JRBId1)
                        .addGap(18, 18, 18)
                        .addComponent(JRBCargo1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(JpanelCargos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JRBId1)
                    .addComponent(JRBCargo1)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnova1)
                    .addComponent(btnsalvar1)
                    .addComponent(btnconsultar1)
                    .addComponent(btnalterar1)
                    .addComponent(btncancelar1))
                .addContainerGap(281, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 510, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 510, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 199, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
        
    private void jPanel1formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1formFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1formFocusGained

    private void jPanel1formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1formComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1formComponentShown

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formFocusGained

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
         
                  
        
            
    }//GEN-LAST:event_formInternalFrameActivated

    private void lblidInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblidInputMethodTextChanged
        // TODO add your handling code here:
    
    }//GEN-LAST:event_lblidInputMethodTextChanged

    private void JRBPgDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBPgDescActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        String dtdescIni,dtdescFin;
       String Desc=null;
       String Pag=null;
        if(VencInicial!=null && VencFinal!=null){
            java.util.Date pega3 =VencInicial.getDate() ;
            dtdescIni=formato.format(pega3);
            SimpleDateFormat formato2 = new SimpleDateFormat("dd-MM-yyyy");
            java.util.Date pega =VencFinal.getDate() ;
            dtdescFin=formato.format(pega);
          MultasBO bo=new MultasBO();
              try{
                  List<Multas> lista=bo.listar(java.sql.Date.valueOf(dtdescIni),java.sql.Date.valueOf(dtdescFin),"Descontadas");
                  DefaultTableModel model = (DefaultTableModel) JTmultas.getModel();
                  JTmultas.removeAll();
                  model.setRowCount(0);
                  for(Multas multa:lista){
                      if(multa.getVecimento()!=null){
                            Desc=formato2.format(multa.getDtdesc());
                        }
                         if(multa.getDtpag()!=null){
                            Pag=formato2.format(multa.getDtpag());
                        }

                      model.addRow(new Object[]{multa.getAIT(),multa.getMatricula(), multa.getValordesc(),Desc,multa.getBoleto(),Pag,multa.getComprovante(),"Incluir comprovante"});
                  }
              }catch(NegocioException ex){

              }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione o periodo da pesquisa!");
        }
    }//GEN-LAST:event_JRBPgDescActionPerformed

    private void JRBPagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBPagasActionPerformed
        // TODO add your handling code here:
       SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        String dtpagIni,dtpagFin;
       String Desc=null;
       String Pag=null;
        if(VencInicial!=null && VencFinal!=null){
            java.util.Date pega3 =VencInicial.getDate() ;
            dtpagIni=formato.format(pega3);
            SimpleDateFormat formato2 = new SimpleDateFormat("dd-MM-yyyy");
            java.util.Date pega =VencFinal.getDate() ;
            dtpagFin=formato.format(pega);
          MultasBO bo=new MultasBO();
              try{
                  List<Multas> lista=bo.listar(java.sql.Date.valueOf(dtpagIni),java.sql.Date.valueOf(dtpagFin),"A Descontar");
                  DefaultTableModel model = (DefaultTableModel) JTmultas.getModel();
                  model.setRowCount(0);
                  for(Multas multa:lista){
                       if(multa.getDtdesc()!=null){
                            Desc=formato2.format(multa.getDtdesc());
                        }else{
                           Desc=null;
                        }
                       
                         if(multa.getDtpag()!=null){
                            Pag=formato2.format(multa.getDtpag());
                        }else{
                             Pag=null;
                         }

                      model.addRow(new Object[]{multa.getAIT(),multa.getValor(),multa.getValordesc(),Desc,multa.getBoleto(),Pag,multa.getComprovante(),"Incluir comprovante"});
                  }
              }catch(NegocioException ex){

              }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione o periodo da pesquisa!");
        }
    }//GEN-LAST:event_JRBPagasActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formInternalFrameClosed

    private void JTmultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTmultasMouseClicked
        // TODO add your handling code here:
    if(JTmultas.getSelectedColumn()==7){
      if( JTmultas.getValueAt(JTmultas.getSelectedRow(),7).equals("Incluir comprovante")){
           JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int i= file.showSaveDialog(null);
        if (i==1){
            JTmultas.setValueAt("", JTmultas.getSelectedRow(), 6);
        } else {
            File arquivo = file.getSelectedFile();
            
            File diretorio = new File("S:\\Multas\\"+ JTmultas.getValueAt(JTmultas.getSelectedRow(),0));
            diretorio.mkdir(); 
           File arquivoExemploOrigem = new File(arquivo.getPath());
           File arquivoExemploDestinoCopiar = new File("S:\\Multas\\"+ JTmultas.getValueAt(JTmultas.getSelectedRow(),0) +"\\Comprovante.pdf");
           try {
           
            //Primeiro modo de copiar o arquivo de um local para outro
            copy(arquivoExemploOrigem, arquivoExemploDestinoCopiar);
            
             } catch (IOException e) {
            e.printStackTrace();
        }
           
            MultasBO bo=new MultasBO();
              try{
                  bo.Comprovante(JTmultas.getValueAt(JTmultas.getSelectedRow() ,0).toString(), arquivoExemploDestinoCopiar.toString());
              }catch(NegocioException ex){

              }
           
           JTmultas.setValueAt(arquivoExemploDestinoCopiar, JTmultas.getSelectedRow(), 6);
        } 
        
      }
      
      
      
    }
     if((JTmultas.getSelectedColumn()==4)&&(!JTmultas.getValueAt(JTmultas.getSelectedRow() ,4).toString().isEmpty())){ 
        try {
            Desktop.getDesktop().open(new File((String) JTmultas.getValueAt(JTmultas.getSelectedRow() ,4)));
        } catch (IOException ex) {
            Logger.getLogger(JFIMultasADescontar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JTmultasMouseClicked
    if((JTmultas.getSelectedColumn()==6)&&(!JTmultas.getValueAt(JTmultas.getSelectedRow() ,6).toString().isEmpty())){ 
        try {
           Desktop.getDesktop().open(new File((String) JTmultas.getValueAt(JTmultas.getSelectedRow() ,6)));
           
        } catch (IOException ex) {
            Logger.getLogger(JFIMultasADescontar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    }
    private void btnnova1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnova1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnova1ActionPerformed

    private void btnsalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsalvar1ActionPerformed

    private void btnconsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnconsultar1ActionPerformed

    private void btnalterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalterar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnalterar1ActionPerformed

    private void btncancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncancelar1ActionPerformed

    private void lblid1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lblid1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lblid1InputMethodTextChanged

    private void JRBId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBId1ActionPerformed

    private void Jtbcargos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jtbcargos1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Jtbcargos1MouseClicked

    private void JRBCargo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBCargo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBCargo1ActionPerformed

    private void jPanel2formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2formFocusGained

    private void jPanel2formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2formComponentShown

    private void jInternalFrame1formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jInternalFrame1formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrame1formFocusGained

    private void jInternalFrame1formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrame1formInternalFrameActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrame1formInternalFrameActivated

    private void jInternalFrame1formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_jInternalFrame1formInternalFrameClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_jInternalFrame1formInternalFrameClosed

    private void JRBTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRBTodasActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
         SimpleDateFormat formato2 = new SimpleDateFormat("dd-MM-yyyy");
        String dtPagIni,dtPagFin;
       String Desc=null;
       String Pag=null;
       
        if(VencInicial!=null && VencFinal!=null){
            java.util.Date pega3 =VencInicial.getDate() ;
            dtPagIni=formato.format(pega3);
            java.util.Date pega =VencFinal.getDate() ;
            dtPagFin=formato.format(pega);
          MultasBO bo=new MultasBO();
              try{
                  
                  List<Multas> lista=bo.listar(java.sql.Date.valueOf(dtPagIni),java.sql.Date.valueOf(dtPagFin),"Todas Pagas");
                  DefaultTableModel model = (DefaultTableModel) JTmultas.getModel();
                  model.setRowCount(0);
                  int linha=1;
                  for(Multas multa:lista){
                        if(multa.getDtdesc()!=null){
                            Desc=formato2.format(multa.getDtdesc());
                        }else{
                            Desc=null;
                        }
                         if(multa.getDtpag()!=null){
                            Pag=formato2.format(multa.getDtpag());
                        }else{
                             Pag=null;
                         }
                  
                      model.addRow(new Object[]{multa.getAIT(),multa.getMatricula(),multa.getValordesc(),Desc,multa.getBoleto(),Pag,multa.getComprovante(),"Incluir comprovante"});
                      JTmultas.getColumnModel().getColumn(7).setPreferredWidth(150);
                     
                     

                     
                  }
              }catch(NegocioException ex){

              }
        }else{
            JOptionPane.showMessageDialog(null, "Selecione o periodo da pesquisa!");
        }
    }//GEN-LAST:event_JRBTodasActionPerformed

    private void cmddtpagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmddtpagActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        String dtdesc;
        if(JDtDesc!=null){
        java.util.Date pega3 =JDtDesc.getDate() ;
            dtdesc=formato.format(pega3);
        int[] selecao = JTmultas.getSelectedRows();
        for (int i = 0; i < selecao.length; i++) {
          
            MultasBO bo=new MultasBO();
              try{
                  bo.Descontar(JTmultas.getValueAt(selecao[i],0).toString(), java.sql.Date.valueOf(dtdesc));
                  if(JRBPgDesc.isSelected()){
                      JRBPgDesc.doClick();
                  }
                  if(JRBPagas.isSelected()){
                      JRBPagas.doClick();
                  }
                  if(JRBTodas.isSelected()){
                      JRBTodas.doClick();
                  }
              }catch(NegocioException ex){

              }
        }
        }else{
            JOptionPane.showMessageDialog(null, "Insira data de pagamento");
        }  
    }//GEN-LAST:event_cmddtpagActionPerformed

    private void cmdboletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdboletosActionPerformed
        // TODO add your handling code here:
        if (JRdSelecionados.isSelected()){
            int[] selecao = JTmultas.getSelectedRows();
            for (int i = 0; i < selecao.length; i++) {
               
                try {
                    if(!JTmultas.getValueAt(selecao[i],4).toString().equals("")){
                        Desktop.getDesktop().print(new File((String) JTmultas.getValueAt(selecao[i],4).toString()));
                    }
                } catch (IOException ex) {
                    Logger.getLogger(JFIMultasADescontar.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }else{
            JTmultas.selectAll();
             int[] selecao = JTmultas.getSelectedRows();
            for (int i = 0; i < selecao.length; i++) {
                
                try {
                    if(!JTmultas.getValueAt(selecao[i],4).toString().isEmpty()){
                        Desktop.getDesktop().print(new File((String) JTmultas.getValueAt(selecao[i],4).toString()));
                    }
                } catch (IOException ex) {
                    Logger.getLogger(JFIMultasADescontar.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_cmdboletosActionPerformed

    private void cmdcomprovantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcomprovantesActionPerformed
        // TODO add your handling code here:
        if (JRdSelecionados.isSelected()){
            int[] selecao = JTmultas.getSelectedRows();
            for (int i = 0; i < selecao.length; i++) {
               
                try {
                    if(!JTmultas.getValueAt(selecao[i],6).toString().equals("")){
                        Desktop.getDesktop().print(new File((String) JTmultas.getValueAt(selecao[i],6).toString()));
                    }
                } catch (IOException ex) {
                    Logger.getLogger(JFIMultasADescontar.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }else{
            JTmultas.selectAll();
             int[] selecao = JTmultas.getSelectedRows();
            for (int i = 0; i < selecao.length; i++) {
                
                try {
                    if(!JTmultas.getValueAt(selecao[i],6).toString().isEmpty()){
                        Desktop.getDesktop().print(new File((String) JTmultas.getValueAt(selecao[i],6).toString()));
                    }
                } catch (IOException ex) {
                    Logger.getLogger(JFIMultasADescontar.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_cmdcomprovantesActionPerformed

public static void copy(File origem, File destino) throws IOException {
        Date date = new Date();
        InputStream in = new FileInputStream(origem);
        OutputStream out = new FileOutputStream(destino);           
        // Transferindo bytes de entrada para saída
        byte[] buffer = new byte[1024];
        int lenght;
        while ((lenght= in.read(buffer)) > 0) {
            out.write(buffer, 0, lenght);
        }
        in.close();
        out.close();
        Long time = new Date().getTime() - date.getTime();
        System.out.println("Saiu copy"+time);
    }
   
    /** 
     * Copia arquivos de um local para o outro 
     * @param origem - Arquivo de origem 
     * @param destino - Arquivo de destino 
     * @param overwrite - Confirmação para sobrescrever os arquivos 
     * @throws IOException 
     */ 
    
    public static void copy(File origem, File destino, boolean overwrite) throws IOException{ 
        Date date = new Date();
       if (destino.exists() && !overwrite){ 
          System.err.println(destino.getName()+" já existe, ignorando..."); 
          return; 
       } 
       FileInputStream fisOrigem = new FileInputStream(origem); 
       FileOutputStream fisDestino = new FileOutputStream(destino); 
       FileChannel fcOrigem = fisOrigem.getChannel();   
       FileChannel fcDestino = fisDestino.getChannel();   
       fcOrigem.transferTo(0, fcOrigem.size(), fcDestino);   
       fisOrigem.close();   
       fisDestino.close(); 
       Long time = new Date().getTime() - date.getTime();
       System.out.println("Saiu copy"+time);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser JDtDesc;
    private javax.swing.JRadioButton JRBCargo1;
    private javax.swing.JRadioButton JRBId1;
    private javax.swing.JRadioButton JRBPagas;
    private javax.swing.JRadioButton JRBPgDesc;
    private javax.swing.JRadioButton JRBTodas;
    private javax.swing.JRadioButton JRdSelecionados;
    private javax.swing.JRadioButton JRdTodos;
    private javax.swing.JTable JTmultas;
    private javax.swing.JPanel JpanelCargos;
    private javax.swing.JPanel JpanelCargos1;
    private javax.swing.JTable Jtbcargos1;
    private com.toedter.calendar.JDateChooser VencFinal;
    private com.toedter.calendar.JDateChooser VencInicial;
    private javax.swing.JButton btnalterar1;
    private javax.swing.JButton btncancelar1;
    private javax.swing.JButton btnconsultar1;
    private javax.swing.ButtonGroup btngpopimp;
    private javax.swing.ButtonGroup btngpordem;
    private javax.swing.JButton btnnova1;
    private javax.swing.JButton btnsalvar1;
    private javax.swing.JButton cmdboletos;
    private javax.swing.JButton cmdcomprovantes;
    private javax.swing.JButton cmddtpag;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblid1;
    private javax.swing.JTextField txtcargo1;
    private javax.swing.JTextField txtcbo1;
    // End of variables declaration//GEN-END:variables

}

